### ISSUE TITLE
请问2022的专业课是不是改成408了

### ISSUE THREAD

**Issue by obrr-hhx** [Jolsonz/hust_kaoyan#1]
在官网也没查到22的招生简章，有点疑惑

**Comment by Jolsonz** [comment]
是的，华科的计算机和网安专业课都改成408了，软院不知道。官网上是有说的，[这个链接](http://www.cs.hust.edu.cn/info/1102/3065.htm)，招生简章貌似要到10月份才出。

**Comment by obrr-hhx** [comment]
十分感谢学长的资料，俺上岸进了东五的云组

**Comment by Jolsonz** [comment]
> 十分感谢学长的资料，俺上岸进了东五的云组

恭喜了。
