### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by speedand** [Jolsonz/hust_kaoyan#2]
请问有往年汇编 数据库 期末试题吗

**Comment by Jolsonz** [comment]
补充了一些，放到`补充资料`下面了

**Comment by speedand** [comment]
> 补充了一些，放到`补充资料`下面了

感谢老哥

**Comment by codesdad** [comment]
您好 请问一下 数据库的第八章以及从第十二章开始就不用看了 是么

**Comment by Jolsonz** [comment]
> 您好 请问一下 数据库的第八章以及从第十二章开始就不用看了 是么

不清楚，时间过得太久了，我做了笔记的当时应该是要考的，比如第八章，redo/undo都还比较重要。
